Edit/delete button only appears if the reviews belongs to logged in user
Calvin087/ironvegan pull request #65
Opened 2022-03-02 19:32 UTC by robertcach

2022-03-02 20:51 UTC, Calvin087 requested changes

2022-03-02 20:51 UTC, Calvin087 commented on config/hbs.config.js
> +hbs.registerHelper("isUserReview", function (options) {
Esta función no está completa, no puedo ejecutar el programa

2022-03-03 16:51 UTC, Calvin087 requested changes

2022-03-03 16:51 UTC, Calvin087 commented on config/hbs.config.js
> +  if (comment.user._id.equals(user._id)) {
Si no estoy logged in y yo quiero ver un detail, el helper en hbs no quiere funcionar.

Yo creo el restaurante que he elegido tiene un comentario, pero el help quiere comprobar si estoy el dueño del comentario. Pero no estoy logged in.

Que method es .equals? De donde sacamos este function/method?
Debería ser === or == ?

2022-03-03 17:05 UTC, Calvin087 commented on controllers/comments.controller.js
> -    if (user == comment.user) {
no necesitamos este prueba?
No puedo encontrar este codigo en el nuevo rama

2022-03-04 12:02 UTC, robertcach commented
@Calvin087 dime porfa si ya ves todo correcto para hacer merge de esta pull.  Gracias!

2022-03-04 17:49 UTC, Calvin087 commented
@robertcach, todovia no puedo ver los detalles si no estoy logged in.

# View Comments 👍🏽
![Screenshot 2022-03-04 at 18 46 11](https://user-images.githubusercontent.com/58273749/156815129-030be1f1-dbf1-4ed4-a2e3-d6c4a9c61dc5.png)

# Delete Comments 👍🏽
![Screenshot 2022-03-04 at 18 46 18](https://user-images.githubusercontent.com/58273749/156815145-92077991-3966-4596-8388-b20a910a2428.png)

# View Details 'not logged in'
![Screenshot 2022-03-04 at 18 46 40](https://user-images.githubusercontent.com/58273749/156815271-bd9641e8-a909-4a21-a18e-cbb05db675e2.png)

# Up to date with delete-reviews rama
![Screenshot 2022-03-04 at 18 48 22](https://user-images.githubusercontent.com/58273749/156815335-9b7b76b0-63ab-4e82-985e-021383946038.png)

2022-03-05 09:34 UTC, robertcach commented
@Calvin087 cuando puedas me dices si te funciona. Gracias!

2022-03-05 10:07 UTC, Calvin087 approved these changes
@robertcach 
por mi bien - MERGE THIS!!! 🎉

Tested:
- logged out view details
- logged in view details
- logged in edit details
- logged in delete

2022-03-05 10:14 UTC, merged